### ISSUE TITLE
hawthorn.master branch

### ISSUE THREAD

**Issue by amirtds** [edx/gradebook#83]
@reillz10 @iloveagent57 I tried to spin up docker env for `hawthorn.master` but it seems there is no `open-release/hawthorn.master` branch for gradebook to be pulled.

**Comment by iloveagent57** [comment]
Hi @amirtds - that's correct, gradebook was only developed in the last several months and isn't supported in the Hawthorn release.  It will be supported in the Ironwood release, which is coming up soon.

**Comment by amirtds** [comment]
Thanks @iloveagent57 for your reply. I will raise the question to docker folks, we may need changes there to don't pull `gradebook` for **hawthorn** version
